version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: event-bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./event_bot.db:/app/event_bot.db
      - ./logs:/app/logs
    depends_on:
      - postgres
    networks:
      - bot-network

  postgres:
    image: postgres:15
    container_name: event-bot-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: event_bot
      POSTGRES_USER: event_bot
      POSTGRES_PASSWORD: event_bot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
