-- Оставляем одну рабочую таблицу partners и перестраиваем её с логичным порядком колонок.
-- Плюс убираем представления partner_stats/task_places_with_partner, чтобы не было лишних "таблиц" в UI.

BEGIN;

DROP VIEW IF EXISTS partner_stats;
DROP VIEW IF EXISTS task_places_with_partner;

ALTER TABLE task_places
DROP CONSTRAINT IF EXISTS task_places_partner_id_fkey;

CREATE TABLE partners_new (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    main_url VARCHAR(255),
    telegram_contact VARCHAR(100),
    telegram_user_id BIGINT,
    default_promo_code VARCHAR(100),
    priority INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    notes TEXT,
    created_at_utc TIMESTAMPTZ DEFAULT NOW(),
    updated_at_utc TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO partners_new (
    id,
    slug,
    display_name,
    main_url,
    telegram_contact,
    telegram_user_id,
    default_promo_code,
    priority,
    is_featured,
    is_active,
    notes,
    created_at_utc,
    updated_at_utc
)
SELECT
    id,
    slug,
    display_name,
    main_url,
    telegram_contact,
    telegram_user_id,
    default_promo_code,
    priority,
    is_featured,
    is_active,
    notes,
    created_at_utc,
    updated_at_utc
FROM partners;

DROP TABLE partners;
ALTER TABLE partners_new RENAME TO partners;

CREATE UNIQUE INDEX IF NOT EXISTS uq_partners_slug_lower ON partners ((LOWER(slug)));

ALTER TABLE task_places
ADD CONSTRAINT task_places_partner_id_fkey
FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_task_places_partner_id ON task_places(partner_id);

SELECT setval(
    pg_get_serial_sequence('partners', 'id'),
    COALESCE((SELECT MAX(id) FROM partners), 1),
    TRUE
);

COMMIT;
