name: "DB Apply (manual)"

on:
  workflow_dispatch:
    inputs:
      sql_path:
        description: "Path to .sql file"
        required: true
        default: "sql/2025_ics_sources_and_indexes.sql"

permissions:
  contents: read

jobs:
  apply:
    name: "Apply SQL using psql"
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: db-apply
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply SQL
        env:
          RAW_DB_URL: ${{ secrets.DATABASE_URL }}
          SQL_PATH: ${{ github.event.inputs.sql_path }}
        run: |
          if [[ -z "$RAW_DB_URL" ]]; then
            echo "DATABASE_URL is empty"; exit 1
          fi
          echo "Applying $SQL_PATH ..."
          psql "$RAW_DB_URL" -v ON_ERROR_STOP=1 -f "$SQL_PATH"
